const canalBIF = require("arraybuffer-loader!../../contents/imagetracks/example.bif");
import { parseBifThumbnails } from "../../../src/experimental/tools";

describe("parseBifThumbnails", () => {
  it("should correctly parse given thumbnails", () => {
    const parsedBIFs = parseBifThumbnails(canalBIF);
    expect(typeof parsedBIFs).toEqual("object");
    expect(parsedBIFs.version).toEqual("0.0.0.0");
    expect(parsedBIFs.images).toBeInstanceOf(Array);
    expect(parsedBIFs.images.length).toEqual(76);
    expect(parsedBIFs.images[0].startTime).toEqual(0);
    expect(parsedBIFs.images[0].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[0].image.byteLength).toEqual(4034);
    expect(parsedBIFs.images[1].startTime).toEqual(1000);
    expect(parsedBIFs.images[1].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[1].image.byteLength).toEqual(4034);
    expect(parsedBIFs.images[2].startTime).toEqual(2000);
    expect(parsedBIFs.images[2].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[2].image.byteLength).toEqual(4034);
    expect(parsedBIFs.images[3].startTime).toEqual(3000);
    expect(parsedBIFs.images[3].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[3].image.byteLength).toEqual(4040);
    expect(parsedBIFs.images[4].startTime).toEqual(4000);
    expect(parsedBIFs.images[4].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[4].image.byteLength).toEqual(4035);
    expect(parsedBIFs.images[5].startTime).toEqual(5000);
    expect(parsedBIFs.images[5].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[5].image.byteLength).toEqual(4035);
    expect(parsedBIFs.images[6].startTime).toEqual(6000);
    expect(parsedBIFs.images[6].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[6].image.byteLength).toEqual(4034);
    expect(parsedBIFs.images[7].startTime).toEqual(7000);
    expect(parsedBIFs.images[7].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[7].image.byteLength).toEqual(1265);
    expect(parsedBIFs.images[8].startTime).toEqual(8000);
    expect(parsedBIFs.images[8].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[8].image.byteLength).toEqual(1265);
    expect(parsedBIFs.images[9].startTime).toEqual(9000);
    expect(parsedBIFs.images[9].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[9].image.byteLength).toEqual(1265);
    expect(parsedBIFs.images[10].startTime).toEqual(10000);
    expect(parsedBIFs.images[10].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[10].image.byteLength).toEqual(4098);
    expect(parsedBIFs.images[11].startTime).toEqual(11000);
    expect(parsedBIFs.images[11].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[11].image.byteLength).toEqual(4446);
    expect(parsedBIFs.images[12].startTime).toEqual(12000);
    expect(parsedBIFs.images[12].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[12].image.byteLength).toEqual(6267);
    expect(parsedBIFs.images[13].startTime).toEqual(13000);
    expect(parsedBIFs.images[13].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[13].image.byteLength).toEqual(4704);
    expect(parsedBIFs.images[14].startTime).toEqual(14000);
    expect(parsedBIFs.images[14].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[14].image.byteLength).toEqual(1450);
    expect(parsedBIFs.images[15].startTime).toEqual(15000);
    expect(parsedBIFs.images[15].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[15].image.byteLength).toEqual(5005);
    expect(parsedBIFs.images[73].startTime).toEqual(73000);
    expect(parsedBIFs.images[73].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[73].image.byteLength).toEqual(1265);
    expect(parsedBIFs.images[74].startTime).toEqual(74000);
    expect(parsedBIFs.images[74].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[74].image.byteLength).toEqual(1265);
    expect(parsedBIFs.images[75].startTime).toEqual(75000);
    expect(parsedBIFs.images[75].image).toBeInstanceOf(ArrayBuffer);
    expect(parsedBIFs.images[75].image.byteLength).toEqual(1265);
  });
});
